FROM python:3.13

ARG MM_USER="museum-map"
ARG MM_UID="10000"
ARG MM_GID="10000"

# Create the user
RUN groupadd --gid $MM_GID $MM_USER && \
    useradd --gid $MM_GID --no-log-init --shell /bin/bash --uid $MM_UID -d /var/lib/museum-map $MM_USER

# Install base dependencies
RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y tini

# Copy the application file
COPY dist/*.whl /tmp/

# Install the application
RUN python -m pip install /tmp/*.whl

RUN mkdir /var/lib/museum-map && \
    mkdir /etc/museum-map && \
    chmod 0755 /var/lib/museum-map && \
    chown -R ${MM_USER}:${MM_USER} /etc/museum-map && \
    chown -R ${MM_USER}:${MM_USER} /var/lib/museum-map

# Setup the running environment
USER ${MM_UID}:${MM_GID}
VOLUME [ "/var/lib/museum-map" ]
ENV LC_ALL=C
WORKDIR /var/lib/museum-map
EXPOSE 8080
ENTRYPOINT [ "tini", "--" ]
CMD [ "uvicorn", "--host", "0.0.0.0", "--port", "8080", "museum_map.server:app" ]
