[tool.poetry]
name = "museum-map"
version = "0.1.0"
description = ""
authors = ["Mark Hall <mark.hall@work.room3b.eu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
inflection = "^0.5.1"
requests = "^2.24.0"
sqlalchemy = "^1.4.0b1"
sqlalchemy_json = "^0.4.0"
lxml = "^4.6.1"
spacy = "^2.3.2"
en-core-web-sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
