[tool.poetry]
name = "museum-map"
version = "0.1.0"
description = ""
authors = ["Mark Hall <mark.hall@work.room3b.eu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
pyramid = "^1.10.4"
pyramid-jinja2 = "^2.8"
pyramid-tm = "^2.4"
sqlalchemy = "^1.3.20"
transaction = "^3.0.0"
zope-sqlalchemy = "^1.3"
waitress = "^1.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
