name: Docker Deployment

on:
  push:
    tags:
      - "v*"

permissions:
  actions: read
  attestations: none
  checks: read
  contents: read
  deployments: none
  id-token: none
  issues: none
  models: none
  discussions: none
  packages: write
  pages: none
  pull-requests: none
  security-events: none
  statuses: none

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Setup Path
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Set up Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv pipx qemu-user-static
          pipx install hatch

      - name: Get application version
        id: get-version
        run: |
          VERSION=`hatch version`
          echo "result=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Application
        run: |
          cd museum_map/server/frontend
          npm install
          npm run build
          cd ../../../
          hatch build

      - name: Build the container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
            image: scmmmh/museum-map
            tags: ${{ steps.get-version.outputs.result }}
            context: .
            containerfiles: |
              ./container/Containerfile
            platforms: linux/arm64/v8,linux/amd64

      - name: Push the container image to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     platforms: linux/amd64,linux/arm64

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: scmmmh
      #     password: ${{ secrets.DOCKERACCESSTOKEN }}

      # - name: Build and Push Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: docker/Dockerfile
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: scmmmh/museum-map:${{ steps.branch_name.outputs.SOURCE_TAG }}
