name: Tests

on:
  push:
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Path
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "PIPX_BIN_DIR=$HOME/.local/bin" >> $GITHUB_ENV

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Set up Node 22.x
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv pipx
          pipx install hatch

      - name: Build Application
        run: |
          cd museum_map/server/frontend
          npm install
          npm run build
          cd ../../../
          hatch build
